name: dependent-gems-test

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths:
    - '.github/workflows/dependent-repos.json'
  pull_request:
    paths:
    - '.github/workflows/dependent-repos.json'
  workflow_dispatch:
  repository_dispatch:
    types: [ release-passed ]

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/dependent-rake.yml@main
    with:
      command: bundle exec rspec
